CXX = g++
CXXFLAGS = -Wall -std=c++17

all: first second

first: first.cpp
	$(CXX) $(CXXFLAGS) first.cpp -o first

second: second.cpp
	$(CXX) $(CXXFLAGS) second.cpp -o second

clean:
	rm -f first second
